
export const ROLE_LABELS: Record<string, string> = {
  mesero: 'Mesero',
  cajero: 'Cajero',
  chef: 'Chef',
  ayudante: 'Ayudante',
  admin: 'Administrador',
};

export const ROLE_PERMISSIONS = {
  mesero: {
    canCreateOrders: true,
    canEditOrders: true,
    canViewOrders: true,
    canProcessPayments: false,
    canManageEmployees: false,
    canViewDashboard: true,
    canEditDashboard: false,
    canAddShoppingNotes: false,
    canChangeOrderStatus: false,
  },
  cajero: {
    canCreateOrders: false,
    canEditOrders: false,
    canViewOrders: true,
    canProcessPayments: true,
    canManageEmployees: false,
    canViewDashboard: true,
    canEditDashboard: false,
    canAddShoppingNotes: false,
    canChangeOrderStatus: false,
  },
  chef: {
    canCreateOrders: false,
    canEditOrders: false,
    canViewOrders: true,
    canProcessPayments: false,
    canManageEmployees: false,
    canViewDashboard: true,
    canEditDashboard: false,
    canAddShoppingNotes: true,
    canChangeOrderStatus: true,
  },
  ayudante: {
    canCreateOrders: false,
    canEditOrders: false,
    canViewOrders: true,
    canProcessPayments: false,
    canManageEmployees: false,
    canViewDashboard: true,
    canEditDashboard: false,
    canAddShoppingNotes: true,
    canChangeOrderStatus: false,
  },
  admin: {
    canCreateOrders: true,
    canEditOrders: true,
    canViewOrders: true,
    canProcessPayments: true,
    canManageEmployees: true,
    canViewDashboard: true,
    canEditDashboard: true,
    canAddShoppingNotes: true,
    canChangeOrderStatus: true,
  },
};
